owner: rmateu
repo: statuspage
user-agent: rmateu
sites:
  - name: 5typos.ne Blog
    url: https://5typos.net
  - name: Statuslog
    url: https://r.mateu.me
  - name: Personal Page
    url: https://roberto.mateu.me
  - name: Ana's Blog
    url: http://anitamarcela.com
#  - name: Secret Site
#   url: $SECRET_SITE
# notifications:
#  - type: slack
#    channel: C016QTU9S9Y
assignees:
  - rmateu
status-website:
  cname: status.mateu.me
  logoUrl: https://micro.blog/roberto/avatar.jpg
  name: Mateu Status Dashboard
  introTitle: "**Status** of my web properties, powered entirely by GitHub."
  introMessage: Uses [Upptime](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
